const app = Vue.createApp({
    data(){
        return {
            first_name: 'Paul',
            last_name: 'Burgess',
            email: 'PaulBurgess@gmail.com',
            username: 'PaulB47',
            //Robohash API
            profile_pic: "https://robohash.org/PaulB47"
        }
    },
    methods: {
        async getUser(){
            //Names & Email generated by https://randomuser.me/  
            const res = await fetch('https://randomuser.me/api')
            const {results} = await res.json()
            console.log(results)
            //-

            this.first_name = results[0].name.first
            this.last_name = results[0].name.last
            this.email= results[0].email
            this.username= this.first_name + this.last_name[0] +Math.floor(Math.random() * 999);
            //Robohash API
            this.profile_pic= "https://robohash.org/" +this.username

            //Color changing
            var r = document.querySelector(':root');
            var rs = getComputedStyle(r);
            //rdm color
            let red = Math.floor(Math.random() * 255)
            let grn = Math.floor(Math.random() * 255)
            let blu = Math.floor(Math.random() * 255)
            //return ``
            r.style.setProperty('--clr-primary', 'rgba('+red+','+grn+','+blu+',1)');
            r.style.setProperty('--clr-secondary', 'rgba('+red+','+grn+','+blu+',0.5)');
            r.style.setProperty('--clr-bg', 'rgba('+red+','+grn+','+blu+',0.1)');
        }
    }

})

app.mount('#app')